export const institutions = [
  "Abubakar Tafawa Balewa University, Bauchi",
  "Ahmadu Bello University, Zaria",
  "Bayero University, Kano",
  "Federal University Gashua, Yobe",
  "Federal University of Petroleum Resources, Effurun",
  "Federal University of Technology, Akure",
  "Federal University of Technology, Minna",
  "Federal University of Technology, Owerri",
  "Federal University, Dutse, Jigawa State",
  "Federal University, Dutsin-Ma, Katsina",
  "Federal University, Kashere, Gombe State",
  "Federal University, Lafia, Nasarawa State",
  "Federal University, Lokoja, Kogi State",
  "Alex Ekwueme University, Ndufu-Alike, Ebonyi State",
  "Federal University, Otuoke, Bayelsa",
  "Federal University, Oye-Ekiti, Ekiti State",
  "Federal University, Wukari, Taraba State",
  "Federal University, Birnin Kebbi",
  "Federal University, Gusau Zamfara",
  "Michael Okpara University of Agricultural Umudike",
  "Modibbo Adama University of Technology, Yola",
  "National Open University of Nigeria, Lagos",
  "Nigeria Police Academy Wudil",
  "Nigerian Defence Academy Kaduna",
  "Nnamdi Azikiwe University, Awka",
  "Obafemi Awolowo University,Ile-Ife",
  "University of Abuja, Gwagwalada",
  "Federal University of Agriculture, Abeokuta",
  "University of Agriculture, Makurdi",
  "University of Benin",
  "University of Calabar",
  "University of Ibadan",
  "University of Ilorin",
  "University of Jos",
  "University of Lagos",
  "University of Maiduguri",
  "University of Nigeria, Nsukka",
  "University of Port-Harcourt",
  "University of Uyo",
  "Usumanu Danfodiyo University",
  "Nigerian Maritime University Okerenkoko, Delta State",
  "Air Force Institute of Technology, Kaduna",
  "Nigerian Army University Biu",
  "Abia State University, Uturu",
  "Adamawa State University Mubi",
  "Adekunle Ajasin University, Akungba",
  "Akwa Ibom State University, Ikot Akpaden",
  "Ambrose Alli University, Ekpoma",
  "Chukwuemeka Odumegwu Ojukwu University, Uli",
  "Bauchi State University, Gadau",
  "Benue State University, Makurdi",
  "Yobe State University, Damaturu",
  "Cross River State University of Technology, Calabar",
  "Delta State University Abraka",
  "Ebonyi State University, Abakaliki",
  "Ekiti State University",
  "Enugu State University of Science and Technology, Enugu",
  "Gombe State Univeristy, Gombe",
  "Ibrahim Badamasi Babangida University, Lapai",
  "Ignatius Ajuru University of Education,Rumuolumeni",
  "Imo State University, Owerri",
  "Sule Lamido University, Kafin Hausa, Jigawa",
  "Kaduna State University, Kaduna",
  "Kano University of Science & Technology, Wudil",
  "Kebbi State University of Science and Technology, Aliero",
  "Kogi State University Anyigba",
  "Kwara State University, Ilorin",
  "Ladoke Akintola University of Technology, Ogbomoso",
  "Ondo State University of Science and Technology Okitipupa",
  "River State University",
  "Olabisi Onabanjo University, Ago Iwoye",
  "Lagos State University, Ojo",
  "Niger Delta University Yenagoa",
  "Nasarawa State University Keffi",
  "Plateau State University Bokkos",
  "Tai Solarin University of Education Ijebu Ode",
  "Umar Musa Yar' Adua University Katsina",
  "Osun State University Osogbo",
  "Taraba State University, Jalingo",
  "Sokoto State University",
  "Yusuf Maitama Sule University Kano",
  "Oyo State Technical University Ibadan",
  "Ondo State University of Medical Sciences",
  "Edo University Iyamo",
  "Eastern Palm University Ogboko, Imo State",
  "University of Africa Toru Orua, Bayelsa State",
  "Bornu State University, Maiduguri",
  "Moshood Abiola University of Science and Technology Abeokuta",
  "Gombe State University of Science and Technology",
  "Zamfara State University",
  "Achievers University, Owo",
  "Adeleke University, Ede",
  "Afe Babalola University, Ado-Ekiti - Ekiti State",
  "African University of Science & Technology, Abuja",
  "Ajayi Crowther University, Ibadan",
  "Al-Hikmah University, Ilorin",
  "Al-Qalam University, Katsina",
  "American University of Nigeria, Yola",
  "Augustine University",
  "Babcock University,Ilishan-Remo",
  "Baze University",
  "Bells University of Technology, Otta",
  "Benson Idahosa University, Benin City",
  "Bingham University, New Karu",
  "Bowen University, Iwo",
  "Caleb University, Lagos",
  "Caritas University, Enugu",
  "Chrisland University",
  "Covenant University Ota",
  "Crawford University Igbesa",
  "Crescent University",
  "Edwin Clark University, Kaigbodo",
  "Elizade University, Ilara-Mokin",
  "Evangel University, Akaeze",
  "Fountain Unveristy, Oshogbo",
  "Godfrey Okoye University, Ugwuomu-Nike - Enugu State",
  "Gregory University, Uturu",
  "Hallmark University, Ijebi Itele, Ogun",
  "Hezekiah University, Umudi",
  "Igbinedion University Okada",
  "Joseph Ayo Babalola University, Ikeji-Arakeji",
  "Kings University, Ode Omu",
  "Kwararafa University, Wukari",
  "Landmark University, Omu-Aran.",
  "Lead City University, Ibadan",
  "Madonna University, Okija",
  "Mcpherson University, Seriki Sotayo, Ajebo",
  "Micheal & Cecilia Ibru University",
  "Mountain Top University",
  "Nile University of Nigeria, Abuja",
  "Novena University, Ogume",
  "Obong University, Obong Ntak",
  "Oduduwa University, Ipetumodu - Osun State",
  "Pan-Atlantic University, Lagos",
  "Paul University, Awka - Anambra State",
  "Redeemer's University, Ede",
  "Renaissance University, Enugu",
  "Rhema University, Obeama-Asa - Rivers State",
  "Ritman University, Ikot Ekpene, Akwa Ibom",
  "Salem University, Lokoja",
  "Samuel Adegboyega University, Ogwa.",
  "Southwestern University, Oku Owa",
  "Summit University",
  "Tansian University, Umunya",
  "University of Mkar, Mkar",
  "Veritas University, Abuja",
  "Wellspring University, Evbuobanosa - Edo State",
  "Wesley University. of Science & Technology, Ondo",
  "Western Delta University, Oghara Delta State",
  "Christopher University Mowe",
  "Kola Daisi University Ibadan, Oyo State",
  "Anchor University Ayobo Lagos State",
  "Dominican University Ibadan Oyo State",
  "Legacy University, Okija Anambra State",
  "Arthur Javis University Akpoyubo Cross river State",
  "Crown Hill University Eiyenkorin, Kwara State",
  "Coal City University Enugu State",
  "Clifford University Owerrinta Abia State",
  "Admiralty University, Ibusa Delta State",
  "Spiritan University, Nneochi Abia State",
  "Precious Cornerstone University, Oyo",
  "PAMO University of Medical Sciences, Portharcourt",
  "Atiba University Oyo",
  "Eko University of Medical and Health Sciences Ijanikin, Lagos",
  "Skyline University, Kano",
  "Akanu Ibiam Federal Polytechnic Unwana, P.M.B 1007, Afikpo, Ebonyi State",
  "Auchi Polytechnic, Auchi, Edo State",
  "Federal Polytechnic Ado Ekiti, Ekiti State",
  "Federal Polytechnic Bali, Taraba State",
  "Federal Polytechnic Bauchi, P.M. B 231, Bauchi State",
  "Federal Polytechnic Bida, P.M.B 55, Niger State",
  "Federal Polytechnic Damaturu, P.M.B 1006, Yobe State",
  "Federal Polytechnic Ede, Osun State",
  "Federal Polytechnic Ekowe, Bayelsa State",
  "Federal Polytechnic Idah, P.M.B 1035, Kogi State",
  "Federal Polytechnic Ilaro, P.M.B 50, Ogun State",
  "Federal Polytechnic Ile-Oluji, Ondo State",
  "Federal Polytechnic Kaura Namoda, P.M.B, 1012, Zamfara State",
  "Federal Polytechnic Mubi, PMB 35 Mubi, Adamawa State",
  "Federal Polytechnic Nasarawa, P.M.B. 01 Nasarawa State",
  "Federal Polytechnic Nekede, P.M.B 1036, Owerri, Imo State",
  "Federal Polytechnic Offa, P.M.B 420, Kwara State",
  "Federal Polytechnic Oko, Anambra State",
  "Federal Polytechnic of Oil and Gas Bonny, Rivers State",
  "Federal Polytechnic Ukana, Akwa Ibom State",
  "Hussaini Adamu Federal Polytechnic, P.M.B 5004, Kazaure Jigawa State",
  "Kaduna Polytechnic, Kaduna",
  "National Institute of Construction Technology Uromi",
  "Waziri Umaru Federal Polytechnic, P.M.B. 1034, Birnin Kebbi",
  "Yaba College of Technology, P.M.B. 2011, Yaba, Lagos State",
  "Airforce Institute of Technology (AFIT), NAF Base Kaduna",
  "Petroleum Training Institute Effurun",
  "Nigerian Army Institute of Technology and Environmental Science (NAITES) Makurdi",
  "Federal School of Dental Technology and Therapy, Enugu, Enugu State",
  "Abdu Gusau Polytechnic, Talata Mafara",
  "Abia State Polytechnic, Aba",
  "Abraham Adesanya Polytechnic, Dogbolu/Akanran Ibadan Road, Atikori, Ijebu Igbo",
  "Abubakar Tatari Ali Polytechnic, Bauchi",
  "Adamawa State Polytechnic, Yola",
  "Akwa Ibom State College of Art & Science, Nung Ukim",
  "Akwa Ibom State Polytechnic",
  "Bayelsa State College of Arts and Science, Elebele",
  "Benue State Polytechnic, Ugbokolo",
  "Binyaminu Usman Polytechnic, Hadejia",
  "Cross River State Institute of Technology And Management, Ugep",
  "D.S. Adegbenro ICT Polytechnic, Itori-Ewekoro, Ogun State",
  "Delta State Polytechnic, Ogwashi-Uku, Delta State",
  "Delta State Polytechnic, Otefe-Oghara, Delta State",
  "Delta State Polytechnic, Ozoro, Delta State",
  "Edo State Institute of Technology and Management, Usen, Edo State",
  "Gateway Polytechnic, Saapade Prof. Wole Soyinka Way, Saapade Estate, Ogun State",
  "Hassan Usman Katsina Polytechnic (HUK), Katsina State",
  "Ibarapa Polytechnic, Eruwa, Oyo State",
  "Imo State Polytechnic, Umuagwo, Ohaji, Imo State",
  "Institute of Management and Technology, Enugu, Enugu State",
  "Jigawa State Polytechnic, Dutse, Jigawa State",
  "Kano State Polytechnic, Kano, Kano State",
  "Ken Sarowiwa Polytechnic, Bori, Rivers State",
  "Kogi State Polytechnic, Lokoja, Kogi State",
  "Kwara State Polytechnic, Ilorin, Kwara State",
  "Lagos State Polytechnic, Ikorodu, Lagos State",
  "Mai-Idris Alooma Polytechnic, Geidam, Yobe State",
  "Nasarawa State Polytechnic, Nasarawa State",
  "Niger State Polytechnic, Zungeru, Niger State",
  "Nuhu Bamalli Polytechnic, Zaria, Kaduna State",
  "Ogun State Institute of Technology, Igbesa, Ogun State",
  "Ogun State Polytechnic, Ipokia, Ogun State",
  "Oke-Ogun Polytechnic, Shaki, Oyo State",
  "Osun State College of Technology, Esa-Oke, Osun State",
  "Osun State Polytechnic, Iree, Osun State",
  "Plateau State Polytechnic, Barkin-Ladi, Plateau State",
  "Port-Harcourt Polytechnic, Rivers State",
  "Ramat Polytechnic, Maiduguri, Borno State",
  "Rufus Giwa Polytechnic, Owo, Ondo State",
  "The Polytechnic Ibadan, Oyo State",
  "Umaru Ali Shinkafi Polytechnic, Sokoto, Sokoto State",
  "Zamfara State College of Arts and Science, Sokoto Road, Zamfara State",
  "Al-Hikma Polytechnic, Karu, Nasarawa State",
  "Allover Central Polytechnic, Sango Ota, Ogun State",
  "Ajayi Polytechnic, Ikere Ekiti, Ekiti State",
  "Ashi Polytechnic, Anyiin, Logo Local Government, Benue State",
  "Best Solution Polytechnic, Akure, Ondo State",
  "Bolmor Polytechnic, Ibadan, Oyo State",
  "Calvary Polytechnic, Owa-Oyibo, Delta State",
  "Citi Polytechnic, FCT Abuja",
  "College of Technology, Iresi, Osun State",
  "Covenant Polytechnic, Aba, Abia State",
  "Crown Polytechnic, Ado-Ekiti, Ekiti State",
  "Dorben Polytechnic, Bwari, Abuja",
  "Eastern Polytechnic, Rivers State",
  "Fidei Polytechnic, Gboko, Benue State",
  "Gboko Polytechnic, Gboko, Benue State",
  "Global Polytechnic, Akure, Ondo State",
  "Grace Polytechnic, Surulere, Lagos State",
  "Heritage Polytechnic, Ikot Udota, Akwa Ibom State",
  "Ibadan City Polytechnic, Oyo State",
  "Igbajo Polytechnic, Igbajo, Osun State",
  "Interlink Polytechnic, Osun State",
  "Kalac Christal Polytechnic, Lekki, Lagos State",
  "Kings Polytechnic, Ubiaja, Edo State",
  "Landmark Polytechnic, Ayetoro/Itele, Ogun State",
  "Lagos City Polytechnic, Ikeja, Lagos State",
  "Lens Polytechnic, Kwara State",
  "Lighthouse Polytechnic, Edo State",
  "Marist Polytechnic, Umuchigbo, Enugu State",
  "Mater Dei Polytechnic, Abia State",
  "Nacabs Polytechnic, Akwanga, Nasarawa State",
  "Nogak Polytechnic, Ikom, Cross River State",
  "Our Saviour Institute of Science, Agriculture & Technology, Enugu",
  "Prime Polytechnic, Jida Bassa, Ajaokuta, Kogi State",
  "Redeemers College of Technology and Management (RECTEM), Lagos State",
  "Ronik Polytechnic, Ejigbo, Lagos State",
  "Saf Polytechnic, Iseyin, Oyo State",
  "Savannah Institute of Technology, Ishieke Junction, Ebonyi State",
  "Shaka Polytechnic, Ogiso, Edo State",
  "St. Mary Polytechnic, Kwamba, Niger State",
  "Sure Foundation Polytechnic, Ikot Akai, Akwa Ibom State",
  "Temple Gate Polytechnic, Abayi, Abia State",
  "The Polytechnic, Igbo-Owu, Kwara State",
  "The Polytechnic, Ile Ife, Osun State",
  "The Polytechnic, Imesi-Ile, Osun State",
  "The Polytechnic, Otada Adoka, Benue State",
  "Tower Polytechnic, Ibadan, Oyo State",
  "Trinity Polytechnic, Uyo, Akwa Ibom State",
  "Uma Ukpai Polytechnic, Asaga Ohafia, Abia State",
  "Uyo City Polytechnic, Uyo, Akwa Ibom State",
  "Valley View Polytechnic, Ohafia, Abia State",
  "Wolex Polytechnic, Iwo, Osun State",
  "Federal College of Education (Technical), Asaba",
  "Federal College of Education, Kano",
  "Federal College of Education (Special), Oyo",
  "Federal College of Education, Abeokuta",
  "Federal College of Education, Eha-Amufu",
  "Federal College of Education (Technical), Gombe",
  "Federal College of Education, Kontagora",
  "Federal College of Education, Okene",
  "Federal College of Education (Technical), Omoku",
  "Federal College of Education (Tech), Potiskum",
  "Alvan Ikoku College of Education, Owerri",
  "Federal College of Education (Technical), Akoka",
  "Federal College of Education (Technical), Bichi",
  "Federal College of Education (Technical), Gusau",
  "Federal College of Education, Katsina",
  "Federal College of Education, Obudu",
  "Adeyemi College of Education, Ondo",
  "Federal College of Education, Pankshin",
  "Federal College of Education, Yola",
  "Federal College of Education, Zaria",
  "Nigerian Army School of Education (NASE), Ilorin",
  "Federal College of Education (T), Umunze",
  "College of Education, Gindiri",
  "Adamawa State College of Education, Hong",
  "Tai Solarin College of Education, Ijebu-Ode",
  "College of Education, Ikere-Ekiti",
  "Ebonyi State College of Education, Ikwo",
  "College of Education, Warri",
  "FCT College of Education, Zuba",
  "Osisatech College of Education, Enugu",
  "Nasarrawa State College of Education, Akwanga",
  "Isa Kaita College of Education, Dutsin-Ma",
  "College of Education, Ekiadolor-Benin",
  "College of Education, Gashua, Damaturu",
  "Kaduna State College of Education, Gidan-Waya, Kafanchan",
  "Osun State College of Education, Ilesa",
  "Kwara State College of Education, Ilorin",
  "College of Education, Katsina-Ala",
  "Sa'adatu Rimi College of Education, Kumbotso, Kano",
  "College of Education (Technical), Lafiagi",
  "Nwafor Orizu College of Education, Nsugbe",
  "Adeniran Ogunsanya College of Education, Otto/Ijanikin",
  "Emmanuel Alayande College of Education (EACOED), Oyo",
  "College of Education, Waka BIU",
  "St. Augustine College of Education (Project Time), Lagos",
  "Delta State College of Education, Agbor",
  "Akwa Ibom State College of Education, Afahansit",
  "Kogi State College of Education, Ankpa",
  "Adamu Augie College of Education, Argungu",
  "College of Education, Azare",
  "Umar Ibn Ibrahim El-Kanemi College of Education, Science and Technology, Bama",
  "College of Education, Jalingo",
  "Zamfara State College of Education, Maru",
  "Jigawa State College of Education, Gumel",
  "Niger State College of Education, Minna",
  "Rivers College of Education, Rumuolumeni",
  "Shehu Shagari College of Education, Sokoto",
  "Jama'Atu College of Education (JACE), Kaduna",
  "College of Education, Arochukwu, Abia",
  "College of Education, Ila-Orangun, Osun State",
  "Michael Otedola College of Prim. Education, Lagos",
  "Kashim Ibrahim College of Education, Maiduguri",
  "Delta State College of Physical Education, Mosogar",
  "Enugu State College of Education (T), Enugu",
  "Cross River State College of Education, Akampa",
  "Edo State College of Education, Igueben",
  "Isaac Jasper Boro College of Education, Sagbama",
  "Kogi State College of Education, Kabba",
  "Institute of Ecumenical Education (Thinkers Corner), Enugu",
  "Delar College of Education",
  "City College of Education, Mararaba, Gurku",
  "Ansar-Ud-Deen College of Education, Isolo",
  "Yewa Central College of Education, Ayetoro",
  "OSISA Tech College of Education, Enugu",
  "St. Augustine College of Education, Lagos",
  "African Thinkers Community of Inquiry, Enugu",
  "Muftau Olanihun College of Education, Ibadan",
  "Havard Wilson College of Education, Aba",
  "Muhyideen College of Education, Ilorin",
  "College of Education, Offa",
  "Bauchi Institute of Arabic & Islamic Studies, Bauchi",
  "Corner Stone College of Education, Lagos",
  "Peaceland College of Education, Enugu",
  "The College of Education, Nsukka",
  "Unity College of Education, Auka Adoka, Benue",
  "Diamond College of Education, Aba",
  "Kinsey College of Education, Ilorin, Kwara State",
  "ECWA College of Education, Jos (ECOEJ)"
];

export const Years =["1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099", "2100"]
